### ISSUE TITLE
Tag and Category Filters Broken Due to Missing Metadata

### ISSUE THREAD

**Issue by TURBODRIVER** [rthaut/deviantART-Filter#103]
Issue #30 states that tag filters were broken, which would render this plugin unusable for me, and I haven't been having any problem for a few weeks of using it. It's a wonderful plugin, thank you. Unfortunately, it eventually broke and tag filtering does not work at all anymore.

I've reviewed issue #58 and issue #102 but the "temporary" solution provided has no effect.
- I've attempted to set the "Number of Days to Cache Metadata" to 0, with no effect, and back to a higher number, with no effect as well. Before restarting Firefox and after restarting Firefox, that did not make a difference.
- I've attempted to alter the "Metadata Batch Size", with no effect.
- I've attempted to remove the plugin, cleared all Firefox cache and cookies, restarted Firefox, and reinstalled the plugin, with no effect. In addition, I have manually searched for any references to DeviantArt within Firefox files to remove related files manually, as well with no effect.
(I'm not aware where data is stored by plugins themselves, so perhaps I could remove even more and test)
- I've attempted to recreate my filters, as well as import my exported data, with no effect.

Can I please be provided with any other possible solutions I could attempt to resolve this issue?

Windows 10 Home
Firefox 67.0.2 (64-bit)
DeviantArt Filter 5.1.1

**Comment by rthaut** [comment]
@TURBODRIVER thanks for the details, especially about what you already did to try to resolve the problem.

The root cause is actually that the DOM structure on DeviantArt recently changed a little bit. There's no visible difference, but the change has caused the metadata injection to fail, so tag and category filters are completely broken.

You can see this by turning on the "Show Metadata Debug Indicators" setting, and noting that not a single thumbnail has a green border.

I hope to get a fix out for this within the next few days. Long-term it seems like this is an area where an improvement can be made to make the metadata functionality less dependent on the DOM structure of DeviantArt.
