### ISSUE TITLE
DeviantArt Eclipse

### ISSUE THREAD

**Issue by rthaut** [rthaut/deviantART-Filter#75]
This is the tracking issue for adding support for [DeviantArt Eclipse](https://www.deviantarteclipse.com/).

Tasks:
- [x] new DOM structure for thumbs
    - [x] update quick-hide button/functionality
    - [x] update CSS selector(s) for filters
    - [x] inject metadata for filters
    - [x] watch for new thumbs loaded via infinite scrolling
- [x] update default placeholder styles
    - Eclipse has two themes (dark and light), but a CSS class is set on the `<body>`
    - ideally come up with one default that works for "old" site and both Eclipse themes

Open Questions:
- Should there be a separate version of the extension for Eclipse? Maybe just for testing purposes?
    - I would prefer to NOT do this, and instead just have one version of the extension that supports both sites, but depending on the extent of the changes needed to support Eclipse, it would be nice to have "beta" testers...
- Should filters be implemented with JS now instead of (or maybe in addition to) CSS?
    - The new DOM structure for thumbs nests the first unique tag (an `<a>` with the deviation's URL) about 3 `<div>`s deeper than the start of the branch for each deviation, so targeting a parent element might be useful (or even necessary)

![deviantart filter for eclipse](https://user-images.githubusercontent.com/5234749/53203475-30ad5f80-3621-11e9-8b91-7c863b99e592.jpg)

**Comment by A-Really-Big-Cat** [comment]
Has there been any progress on getting this to work?

To be honest I don't particularly like Eclipse anyway, its usability is sub-par at best compared to the classic format.

**Comment by rthaut** [comment]
I have not really made any progress on this.

I did submit feedback to the Eclipse team (a few months ago now) asking for them to implement something that would tremendously benefit this extension. If they do implement my request, the solution for this extension to support Eclipse would be dramatically different than if they do not, so I was hoping to wait until that request is either implemented or denied. Unfortunately, I have not yet heard back one way or the other.

**Comment by A-Really-Big-Cat** [comment]
Aw man, that’s always a pain. Best of luck! Rory McKay From: Ryan ThautSent: November 20, 2019 3:32 PMTo: rthaut/deviantART-FilterCc: A-Really-Big-Cat; CommentSubject: Re: [rthaut/deviantART-Filter] DeviantArt Eclipse (#75) I have not really made any progress on this.I did submit feedback to the Eclipse team (a few months ago now) asking for them to implement something that would tremendously benefit this extension. If they do implement my request, the solution for this extension to support Eclipse would be dramatically different than if they do not, so I was hoping to wait until that request is either implemented or denied. Unfortunately, I have not yet heard back one way or the other.—You are receiving this because you commented.Reply to this email directly, view it on GitHub, or unsubscribe.

**Comment by rthaut** [comment]
Updates for the [open questions listed above](https://github.com/rthaut/deviantART-Filter/issues/75#issue-413136255):

> Should there be a separate version of the extension for Eclipse? Maybe just for testing purposes?

There will not be a separate version for Eclipse. DeviantArt has [announced the classic version will be deprecated in May](https://www.deviantartsupport.com/en/article/new-deviantart-launch-late-may). The current alpha builds work with both classic and Eclipse, but priority for functionality has been given to Eclipse.

> Should filters be implemented with JS now instead of (or maybe in addition to) CSS?

Filters are added/applied to thumbnails using JS, but CSS is used to style the placeholders.

**Comment by TURBODRIVER** [comment]
Bravo, wonderful work!
